# -*- coding: utf-8 -*-
"""kellycriterion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16z_49UjvZCFeQmGNqCkUAdQ8KZYnJfuG
"""

# dependencies
import random

# starting settings
balance = 25 # Starting Balance 
count = 5 # number of rounds needed (In experiment, they used 300)
rnd = 1

while count != 0:

  print("\nRound",rnd,"| Rem:",count-1,"\n")

  # bet amount
  bet = input("Amount: ")

  # getting head or tail input from user
  choice = input("\nPress 0 for Tail\nPress 1 for Head\n Option: ")

  # type casting variable into integer type
  choice = int(choice)
  bet = int(bet)

  # simulating a coin toss
  a_list = [0,1]
  distribution = [.4,.6]
  coin = random.choices(a_list, distribution)
  if coin[0] == 0:
    print("\n*flips coin*")
    print("...")
    print("Tail")

  elif coin[0] == 1:
    print("\n*flips coin*")
    print("...")
    print("Head")

  # checking if the predictions match
  if coin[0] == choice:
    print("\nThe coin tossed in your favour")
    pl = bet*2
    balance = balance + pl
    print("\nBalance: ",balance,"| P/L: +",pl, "| Bet Amount:", bet)
    bet = 0

  elif coin[0] != choice:
    print("\nThe coin tossed against your favour")
    pl = -bet
    balance = balance + pl
    print("\nBalance: ",balance,"| P/L: ",pl, "| Bet Amount:", bet)
    bet = 0

  rnd = rnd + 1
  count = count - 1